// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-nvFDZ5DrDenbDQ-u3ZHulKWlH_eHnQU',
    appId: '1:300816474921:web:1e41b063933528f0e7cd38',
    messagingSenderId: '300816474921',
    projectId: 'project-chat-app-72db0',
    authDomain: 'project-chat-app-72db0.firebaseapp.com',
    storageBucket: 'project-chat-app-72db0.appspot.com',
    measurementId: 'G-P3RD9DBVTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXWRX8J_FKl6J7nQadv-dmzEgACuAph5Q',
    appId: '1:300816474921:android:5f45b2a24fee188ae7cd38',
    messagingSenderId: '300816474921',
    projectId: 'project-chat-app-72db0',
    storageBucket: 'project-chat-app-72db0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7T7-fGW340IySvHqgpvZqYTu0yFFHsbs',
    appId: '1:300816474921:ios:1b285984a90efa19e7cd38',
    messagingSenderId: '300816474921',
    projectId: 'project-chat-app-72db0',
    storageBucket: 'project-chat-app-72db0.appspot.com',
    iosClientId: '300816474921-vlp5k0va32mnulvjgajnr74c2g5ndv7f.apps.googleusercontent.com',
    iosBundleId: 'com.dusty.projectChatApp',
  );
}
